# Generated by Django 5.2.7 on 2025-10-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_project_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Features',
        ),
    ]
